### ISSUE TITLE
Suggestion: Fall back to count actual flow of items

### ISSUE THREAD

**Issue by Archangel33** [MarcioHuser/EfficiencyCheckerMod-SML3#20]
Suggestion

In instances where Injected input can not be calculated from the machines that produced the items, due to some sort of belt balancing setup, it would be very beneficial  to replace the blank ("-- items/min")  input value with the count of items actually flowing through the checker.

If it can't be a fall back a check box option in the interface to either count flowing items or count via attached machine output would also work. 

I understand that this is a very different approach to calculating the displayed information, but I can't over-state how useful it would be to have this value while debugging.  This would give us an idea how big of a problem we have, if its off by one or two items/m then I'm not too worried, however the larger the difference the more important it is for me to fix it. I know there are other mods that do this, however the Wall checker form factor is very convenient, and by far my preferred choice. 

Thank you for the mod and your consideration.

**Comment by MarcioHuser** [comment]
It will never count the actual throughput through it, because it does not interect with the belt in anyway to get that information. BUT, if you are sure about the injected/consumed numbers in that belt, you can just type a fixed value for it. It will show in blue to indicate it is a fixed manual value
